### ISSUE TITLE
Crash after winning battle

### ISSUE THREAD

**Issue by stbeaumont98** [SCCapstone/turn-based-rpg#264]
Similar to #258, I am unable to progress the game any further after a battle is complete. The only exception to this is the scarecrow battles in Platzhalter Village.

![Screenshot 2024-04-13 233231](https://github.com/SCCapstone/turn-based-rpg/assets/59749228/d669a180-c316-4170-ae5f-bc7421e78174)

Perhaps the Code Error can help you guys figure out how to resolve this?

**Comment by chris-moore-dev** [comment]
@stbeaumont98 What kind of computer were you using when you ran into this bug? Was your whole team running into this issue? We cannot reproduce the bug on our end.

**Comment by stbeaumont98** [comment]
Happens on both my machines.
My laptop: Surface Book 2, i7-8650U, 8GB RAM, 64-bit Windows 11 Pro
My PC: i7-9700K, 64GB RAM, 64-bit Windows 11 Pro

Not sure what other info I could provide that would be helpful.

**Comment by chris-moore-dev** [comment]
Very bizarre, still nobody on our team can reproduce the same issue. Will have to keep looking. Thank you for the info though.

**Comment by chris-moore-dev** [comment]
Issue cannot be replicated
