### ISSUE TITLE
Game Freezes when the Player decides not to Save or End Game

### ISSUE THREAD

**Issue by JasonHoangTran** [SCCapstone/turn-based-rpg#270]
The game freezes (none of the controls do anything) when the player opens up the pause menu with 'p', then pressing 'e' to open up the save and end game options, and then pressing the escape key to attempt to go back to the navigating the pause menu. 

![turnedbasedrpg_bugpic](https://github.com/SCCapstone/turn-based-rpg/assets/77406558/a938ba1c-4049-4188-bd26-30ffb2dd9d3a)

**Comment by EthanWatkins1720** [comment]
Same as #260, saving first does not make a difference. Closed for this reason.
