### ISSUE TITLE
Player unable to Recruit after Battling Scarecrows

### ISSUE THREAD

**Issue by JasonHoangTran** [SCCapstone/turn-based-rpg#273]
To recreate this, I went straight to the scarecrows after loading the game, battled one of them, then went to talk to the wizard and mercenary, tried to recruit them (the dialog box says I recruited them and their sprites didn't disappeared), and finally I went back to battle the scarecrows and the wizard and mercenary weren't in my party.

https://github.com/SCCapstone/turn-based-rpg/assets/77406558/1b8e6250-c669-4403-9638-5270c02f796f

**Comment by EthanWatkins1720** [comment]
Same as #263
