### ISSUE TITLE
Resizing the game window stretches assets

### ISSUE THREAD

**Issue by CMartin2288** [SCCapstone/turn-based-rpg#277]
With the game in windowed mode, drag the edges of the window to resize it. Doing so causes the game to get stretched or squished.

https://github.com/SCCapstone/turn-based-rpg/assets/97468361/a7d0ff50-5918-4e06-bd4d-d065a0e8eba5

**Comment by chris-moore-dev** [comment]
Not worth fixing, as the alternative is disallowing window resizing.
