### ISSUE TITLE
Battle screen text misplaced on screen

### ISSUE THREAD

**Issue by ClarkRM** [SCCapstone/turn-based-rpg#279]
The "Battle" screen off of the pause menu in the map has the HP of each enemy overlapping the enemy sprites
![Created with GameMaker 4_14_2024 9_20_33 PM](https://github.com/SCCapstone/turn-based-rpg/assets/70110582/d4b66440-683c-45e5-b14b-038112aebc0c)

**Comment by chris-moore-dev** [comment]
Resolved by 8ecdcc5
